# Generated by Django 4.1.2 on 2022-10-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_donation_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_blogs',
            name='category_object',
            field=models.CharField(choices=[('CLOTHES', 'Clothes'), ('SHOSE', 'Shose'), ('FOOD', 'Food'), ('DRUG', 'Drug'), ('APPLIANCE', 'Appliance')], default='APPLIANCE', max_length=50),
        ),
        migrations.AlterField(
            model_name='donation_blogs',
            name='category_user',
            field=models.CharField(choices=[('KID', 'Kid'), ('ADULT', 'Adult'), ('GRAYBEARD', 'Graybeard'), ('CRIPPLE', 'Cripple')], default='KID', max_length=50),
        ),
    ]
