# Generated by Django 4.1.2 on 2022-10-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_donation_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_blogs',
            name='category_object',
            field=models.CharField(choices=[('เสื้อผ้า', 'Clothes'), ('รองเท้า', 'Shose'), ('อาหารและยา', 'Fooddrug'), ('ของใช้', 'Appliance'), ('เงินบริจาค', 'Donate')], default='ของใช้', max_length=50),
        ),
        migrations.AlterField(
            model_name='donation_blogs',
            name='category_user',
            field=models.CharField(choices=[('เด็กเล็ก', 'Smallkid'), ('เด็กโต', 'Kid'), ('สัตว์เลี้ยง', 'Pets'), ('คนชรา', 'Graybeard'), ('คนพิการ', 'Cripple')], default='เด็กโต', max_length=50),
        ),
    ]
