# Generated by Django 4.1.2 on 2022-10-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_donation_blogs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_blogs',
            name='description',
            field=models.TextField(),
        ),
    ]
