# Generated by Django 4.1.2 on 2022-10-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_donation_blogs_category_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_blogs',
            name='category_object',
            field=models.CharField(choices=[('เสื้อ', 'Clothes'), ('รองเท้า', 'Shose'), ('อาหารและยา', 'Foodanddrug'), ('เงินบริจาค', 'Donation'), ('ของใช้', 'Appliance')], default='ของใช้', max_length=50),
        ),
        migrations.AlterField(
            model_name='donation_blogs',
            name='category_user',
            field=models.CharField(choices=[('เด็ก', 'Kid'), ('เด็กโต', 'Teenager'), ('ผู้ใหญ่', 'Adult'), ('คนชรา', 'Graybeard'), ('คนพิการ', 'Cripple')], default='เด็ก', max_length=50),
        ),
    ]
