# Generated by Django 4.1.2 on 2022-11-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_donation_blogs_category_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_blogs',
            name='category_object',
            field=models.CharField(choices=[('เสื้อผ้า', 'Clothes'), ('กางเกง', 'Trousers'), ('รองเท้า', 'Shose'), ('อาหารและยา', 'Foodanddrug'), ('เงินบริจาค', 'Donation'), ('ของใช้', 'Appliance')], default='ของใช้', max_length=50),
        ),
    ]
