# Generated by Django 4.1.2 on 2022-11-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_donation_blogs_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_blogs',
            name='report',
            field=models.IntegerField(default=0),
        ),
    ]
