# Generated by Django 4.1 on 2022-09-07 09:27

from asyncio.windows_events import NULL
from msilib import Table
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
            ],
        ),
    ]

CREATE TABLE "members_members"(
"id" INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
"firstname" VARCHAR(255) NOT NULL,
"lastname" VARCHAR(255) NOT NULL);
