# Generated by Django 4.1.2 on 2022-10-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation_blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('write', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reason', models.TextField()),
                ('location', models.TextField()),
                ('Amount_requested', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='blogImages')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('category_object', models.CharField(choices=[('เสื้อผ้า', 'Clothes'), ('รองเท้า', 'Shose'), ('อาหาร', 'Food'), ('ยา', 'Drug'), ('ของใช้', 'Appliance')], default='ของใช้', max_length=50)),
                ('category_user', models.CharField(choices=[('เด็ก', 'Kid'), ('ผู้ใหญ่', 'Adult'), ('คนชรา', 'Graybeard'), ('คนพิการ', 'Cripple')], default='เด็ก', max_length=50)),
            ],
        ),
    ]
