# Generated by Django 4.1.2 on 2022-10-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_blogs',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
